import type { Persona, WishlistItem } from "../src/types";

// Simulated data, derived from primary research personas — not real users.
// requirement #10: this must be labelled in the UI itself (SimulatedDataLabel),
// not only in the deck.
//
// Personas: derived from the 6 real interview subjects + survey segments in
// docs/research-findings.md (not generic archetypes).
//
// Product images: AI-generated sample imagery for MVP demonstration only,
// not real product photography. Sourced via mvp/public/product-images/
// (see manifest.json there). No live API call at runtime, no key anywhere.
//
// Round 2 item 2 (gender-curated wishlists): each persona's items are now
// single-gender or unisex, no mixing. This moved 3 items between personas
// from the original assignment — the ORIGINAL images stayed with the SAME
// interview-derived persona story (price-timing-waiter etc.), only which
// specific items populate that story changed: "Wide-Leg Jeans" and "Olive
// Trousers" moved from price_timing_waiter to inspiration_moodboard_saver
// (both women's-coded images), and "Navy Cable-Knit Sweater" moved from
// inspiration_moodboard_saver to price_timing_waiter (men's-coded image) —
// their narration was rewritten to fit their new persona's actual barrier,
// since the item's story must match whichever persona now owns it.
//
// Round 2 item 7: trace summaries no longer use internal pipeline jargon
// ("cluster", finding-ID citations) in any user-facing string — findingId
// stays as an internal data key only (AITraceWidget no longer renders it).

function productImage(filename: string): string {
  return `/product-images/${filename}.png`;
}

// Relative to "now" so the WhyNowBadge's ~48h age gate demos correctly
// whenever this is viewed, rather than going stale against a hardcoded date.
function hoursAgo(n: number): string {
  return new Date(Date.now() - n * 60 * 60 * 1000).toISOString();
}

export const PERSONAS: Persona[] = [
  {
    id: "price_timing_waiter",
    name: "Price-Timing Waiter",
    description:
      "“If it was 1,200 I probably would've bought it then and there.” Likes the product, waits for a specific price. Deliberately deferred, not forgotten.",
    barrier: "Blocked by price, not interest — waiting for a specific discount before buying.",
    researchNote: "Based on shopper interviews about price-waiting behavior.",
  },
  {
    id: "fit_cautious_returner",
    name: "Fit-Cautious Returner",
    description:
      "“I don't want to buy and then return.” Blocked by sizing uncertainty, avoids the buy-two-sizes hassle.",
    barrier: "Blocked by sizing uncertainty — wants to be sure it fits before ordering, not after.",
    researchNote: "Based on a shopper interview about sizing anxiety and return hassle.",
  },
  {
    id: "occasion_driven",
    name: "Occasion-Driven Saver",
    description:
      "“Do I actually have a life for this dress?” Purchase is gated on a real event materializing, not on the product itself.",
    barrier: "Blocked by timing — the purchase only makes sense once a real event shows up.",
    researchNote: "Based on a shopper interview about buying for a specific event.",
  },
  {
    id: "quality_evidence_seeker",
    name: "Quality-Evidence Seeker",
    description:
      "“More reviews vs. better evidence” — wants a synthesized quality verdict, not 200 reviews to read herself.",
    barrier: "Blocked by doubt about material quality — wants a clear verdict, not raw reviews to sift through.",
    researchNote: "Based on a shopper interview about wanting proof of quality before spending.",
  },
  {
    id: "inspiration_moodboard_saver",
    name: "Inspiration / Moodboard Saver",
    description:
      "“More like a moodboard than a shopping list.” Saves for ideas, not near-term purchase — a real but minority pattern (about 1 in 10 saves, by survey and interview).",
    barrier: "Not really blocked — most of these saves were never near-term purchase intent to begin with.",
    researchNote: "Based on a shopper interview and a wider survey of shoppers about why they save items.",
  },
];

function priceTimingWaiterItems(): WishlistItem[] {
  return [
    {
      // Restored to Price-Timing Waiter: this is P1's own literal example
      // ("wide-leg jeans", waiting for the price to drop) from docs/
      // research-findings.md — moving it elsewhere and rewriting its
      // reasoning would contradict that real, documented evidence. Treated
      // as the unisex-style exception (like sneakers/totes) for the item-2
      // gender-curation pass, since jeans as a category isn't gendered the
      // way a dress or blazer is.
      id: "ptw-1",
      name: "Wide-Leg Jeans",
      brand: "Studio Denim Co.",
      category: "Jeans",
      imageUrl: productImage("01_wideleg_jeans"),
      imageAlt: "Wide-leg jeans, product photography on plain background",
      price: "₹1,799",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 6),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "high",
      comparisonRows: [{ label: "TYPICAL PRICE", before: "₹1,799", after: "₹1,799", delta: "0%" }],
      priceHistory: [1799, 1799, 1799, 1799, 1799],
      narration:
        "This has held at ₹1,799 for 3 weeks straight — no sale pattern detected recently, so waiting further is unlikely to move the price.",
      trace: { findingId: "INT-P1", summary: "Waiting for a specific price, not affordability, before buying." },
    },
    {
      id: "ptw-2",
      name: "White Sneakers",
      brand: "Fieldwalk",
      category: "Sneakers",
      imageUrl: productImage("02_white_sneakers"),
      imageAlt: "White sneakers, product photography on plain background",
      price: "₹2,999",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 9),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "medium",
      comparisonRows: [{ label: "TYPICAL PRICE", before: "₹3,499", after: "₹2,999", delta: "-14%" }],
      priceHistory: [3499, 3499, 3299, 3199, 2999],
      narration:
        "Down 14% from its typical price, but short of the ~20-25% drop this kind of wait usually targets — not quite there yet.",
      missingForHigherConfidence: "No prior discount cycle on file for this exact style to confirm 2,999 is close to its floor.",
      trace: { findingId: "INT-P6", summary: "Waiting for a specific target discount before buying, not just any markdown." },
    },
    {
      id: "ptw-3",
      name: "Black Sneakers",
      brand: "Fieldwalk",
      category: "Sneakers",
      imageUrl: productImage("03_black_sneakers"),
      imageAlt: "Black sneakers, product photography on plain background",
      price: "₹2,999",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 20),
      stock: "low_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      priceHistory: [2999, 2999, 2999, 2999],
      narration: "",
      whatWouldHelp: "No price-history data yet for this specific colourway — one more sale cycle would let us compare confidently.",
      trace: { findingId: "INT-P6", summary: "Low in stock with no price-history baseline yet for this colourway." },
    },
    {
      id: "ptw-5",
      name: "Black Oversized Tee",
      brand: "Studio Denim Co.",
      category: "Tees",
      imageUrl: productImage("05_black_oversized_tee_m"),
      imageAlt: "Black oversized t-shirt, product photography on plain background",
      price: "₹799",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 30),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "medium",
      comparisonRows: [{ label: "TYPICAL PRICE", before: "₹899", after: "₹799", delta: "-11%" }],
      priceHistory: [899, 899, 849, 819, 799],
      narration: "Small dip, but this shopper's own pattern is to wait for larger cuts — not yet at the level that historically triggers a buy.",
      missingForHigherConfidence: "Only one prior price point on file — can't confirm this is near the floor.",
      trace: { findingId: "INT-P1", summary: "Partial discount so far, below the level that usually triggers a purchase here." },
    },
    {
      id: "ptw-6",
      name: "White Linen Shirt",
      brand: "Fieldwalk",
      category: "Shirts",
      imageUrl: productImage("06_white_linen_shirt_m"),
      imageAlt: "White linen shirt, product photography on plain background",
      price: "₹1,299",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 6),
      stock: "back_in_stock",
      restockedAt: hoursAgo(24 * 2),
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      priceHistory: [1299, 1299, 1299],
      narration: "",
      whatWouldHelp:
        "This came back in stock 2 days ago after being unavailable — a real signal, though we still don't have a post-restock price point to confirm whether the price will move too.",
      trace: { findingId: "INT-P1", summary: "Just restocked after being unavailable — too soon to have post-restock price data." },
    },
    {
      id: "ptw-7",
      name: "Navy Cable-Knit Sweater",
      brand: "Northfield",
      category: "Sweaters",
      imageUrl: productImage("27_navy_cableknit_sweater_m"),
      imageAlt: "Navy cable-knit sweater, product photography on plain background",
      price: "₹2,199",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 2),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "medium",
      comparisonRows: [{ label: "TYPICAL PRICE", before: "₹2,499", after: "₹2,199", delta: "-12%" }],
      priceHistory: [2499, 2499, 2399, 2299, 2199],
      narration: "Down 12% from typical — inside the range this shopper watches, though not yet at the ~20-25% drop that usually closes the deal.",
      missingForHigherConfidence: "No prior discount cycle on file for this exact style to confirm 2,199 is close to its floor.",
      trace: { findingId: "INT-P1", summary: "Price is moving in the right direction but hasn't hit the usual buying threshold yet." },
    },
  ];
}

function fitCautiousReturnerItems(): WishlistItem[] {
  return [
    {
      id: "fcr-1",
      name: "Denim Jacket",
      brand: "Kerne & Fold",
      category: "Jackets",
      imageUrl: productImage("07_denim_jacket_m"),
      imageAlt: "Denim jacket, product photography on plain background",
      price: "₹2,199",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 4),
      stock: "low_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "high",
      comparisonRows: [
        { label: "CHEST", before: "40\"", after: "40\"", delta: "0\"" },
        { label: "LENGTH", before: "26\"", after: "26\"", delta: "0\"" },
      ],
      narration: "Matches your last 2 kept jackets from this brand exactly — same size, same fit family, no relaxed-fit ambiguity here.",
      trace: { findingId: "INT-P2", summary: "Exact brand and size match — avoids the buy-two-sizes-and-return workaround." },
    },
    {
      id: "fcr-2",
      name: "Beige Blazer",
      brand: "Kerne & Fold",
      category: "Blazers",
      imageUrl: productImage("08_beige_blazer_m"),
      imageAlt: "Beige blazer, product photography on plain background",
      price: "₹3,499",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 7),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "medium",
      comparisonRows: [{ label: "CHEST", before: "40\"", after: "41\"", delta: "+1\"" }],
      narration: "Chest measurement is close but not exact — listed as 'relaxed fit', which has run oversized on similar pieces before.",
      missingForHigherConfidence: "No shoulder or sleeve-length data for this style to confirm the relaxed cut won't run large.",
      trace: { findingId: "INT-P2", summary: "A relaxed-fit label has meant an oversized result before — same ambiguity here." },
    },
    {
      id: "fcr-3",
      name: "Gray Formal Trousers",
      brand: "Kerne & Fold",
      category: "Trousers",
      imageUrl: productImage("09_gray_formal_trousers_m"),
      imageAlt: "Gray formal trousers, product photography on plain background",
      price: "₹1,999",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 1),
      stock: "low_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "No past formal-trouser purchases from this brand — a fit photo or one past purchase would let us compare rise and length confidently.",
      trace: { findingId: "INT-P2", summary: "No comparable purchase history from this brand in this category yet." },
    },
    {
      id: "fcr-4",
      name: "Striped Shirt",
      brand: "Meridian",
      category: "Shirts",
      imageUrl: productImage("10_striped_shirt_m"),
      imageAlt: "Striped shirt, product photography on plain background",
      price: "₹1,199",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 15),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "medium",
      comparisonRows: [{ label: "CHEST", before: "40\"", after: "39\"", delta: "-1\"" }],
      narration: "Runs slightly closer-fit than what you've kept before — within a size correction, but not an exact match.",
      missingForHigherConfidence: "Only one past Meridian purchase on file — more history would sharpen this.",
      trace: { findingId: "INT-P2", summary: "A near match on fit, but based on only one past purchase from this brand." },
    },
    {
      id: "fcr-5",
      name: "Charcoal Wool Jacket",
      brand: "Kerne & Fold",
      category: "Jackets",
      imageUrl: productImage("16_charcoal_wool_jacket_m"),
      imageAlt: "Charcoal wool jacket, product photography on plain background",
      price: "₹4,299",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 5),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: "2026-08-22T14:00:00Z",
      confidence: "high",
      comparisonRows: [
        { label: "CHEST", before: "40\"", after: "40\"", delta: "0\"" },
        { label: "SHOULDER", before: "18\"", after: "18\"", delta: "0\"" },
      ],
      narration: "Exact match on chest and shoulder to your 2 kept jackets from this brand — the return-avoidance case this shopper is looking for.",
      trace: { findingId: "INT-P2", summary: "Exact fit match on chest and shoulder against past kept purchases." },
    },
    {
      id: "fcr-6",
      name: "Charcoal Formal Trousers",
      brand: "Meridian",
      category: "Trousers",
      imageUrl: productImage("28_charcoal_formal_trousers_m"),
      imageAlt: "Charcoal formal trousers, product photography on plain background",
      price: "₹2,099",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 25),
      stock: "out_of_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "Out of stock in your size — no fit data to compare even if it restocks; a save that may decay before it ever resolves.",
      trace: { findingId: "INT-P2", summary: "Out of stock in the needed size, compounding the existing fit uncertainty." },
    },
  ];
}

function occasionDrivenItems(): WishlistItem[] {
  return [
    {
      id: "od-1",
      name: "Burgundy Wrap Dress",
      brand: "Verre",
      category: "Dresses",
      imageUrl: productImage("11_burgundy_wrap_dress"),
      imageAlt: "Burgundy wrap dress, product photography on plain background",
      price: "₹3,299",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 12),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "No event on the calendar yet to match this against — the purchase only makes sense once one shows up.",
      trace: { findingId: "INT-P5", summary: "Purchase is gated on a real event materializing, not on the product itself." },
    },
    {
      id: "od-2",
      name: "Gold Satin Slip Dress",
      brand: "Verre",
      category: "Dresses",
      imageUrl: productImage("12_gold_satin_slip_dress"),
      imageAlt: "Gold satin slip dress, product photography on plain background",
      price: "₹4,199",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 4),
      stock: "back_in_stock",
      restockedAt: hoursAgo(24 * 1),
      addedToCartAt: null,
      confidence: "high",
      comparisonRows: [{ label: "BUST", before: "32\"", after: "32\"", delta: "0\"" }],
      narration: "Came back in stock yesterday after being unavailable, and an event just landed on the calendar — same fit family as a past kept purchase from this brand.",
      trace: { findingId: "INT-P5", summary: "Restocked right as a real event appeared — both conditions this shopper needs are now met." },
    },
    {
      id: "od-3",
      name: "Navy Floral Dress",
      brand: "Ilana",
      category: "Dresses",
      imageUrl: productImage("13_navy_floral_dress"),
      imageAlt: "Navy floral dress, product photography on plain background",
      price: "₹2,899",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 18),
      stock: "low_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "medium",
      comparisonRows: [{ label: "BUST", before: "32\"", after: "33\"", delta: "+1\"" }],
      narration: "Close fit match, but no occasion pending — low stock means this one may decay before an event does arrive.",
      missingForHigherConfidence: "No specific event on file to confirm timing — only the fit side of this can be compared with confidence.",
      trace: { findingId: "INT-P5", summary: "Fit is resolved, but the occasion this purchase depends on still isn't." },
    },
    {
      id: "od-4",
      name: "Black Ankle-Strap Heels",
      brand: "Verre",
      category: "Heels",
      imageUrl: productImage("14_black_ankle_strap_heels"),
      imageAlt: "Black ankle-strap heels, product photography on plain background",
      price: "₹2,599",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 6),
      stock: "low_stock",
      restockedAt: null,
      addedToCartAt: "2026-08-23T18:00:00Z",
      confidence: "high",
      comparisonRows: [{ label: "SIZE", before: "38", after: "38", delta: "0" }],
      narration: "Same size as a kept pair, and an event is on the calendar — both conditions this shopper needs are met.",
      trace: { findingId: "INT-P5", summary: "Both fit and occasion are resolved at the same time." },
    },
    {
      id: "od-5",
      name: "Sparkly Clutch",
      brand: "Ilana",
      category: "Bags",
      imageUrl: productImage("15_sparkly_clutch"),
      imageAlt: "Sparkly evening clutch, product photography on plain background",
      price: "₹1,499",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 22),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "Styling accessories like this don't have a size-fit signal at all — the only real gate here is whether an occasion shows up.",
      trace: { findingId: "INT-P5", summary: "An accessory saved ahead of any specific event — occasion is the only real gate." },
    },
  ];
}

function qualityEvidenceSeekerItems(): WishlistItem[] {
  return [
    {
      id: "qes-1",
      name: "Black Crew Sweater",
      brand: "Northfield",
      category: "Sweaters",
      imageUrl: productImage("17_black_crew_sweater_m"),
      imageAlt: "Black crew-neck sweater, product photography on plain background",
      price: "₹1,899",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 5),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "high",
      comparisonRows: [],
      narration: "Across 140 reviews, the recurring finding is 'thicker than expected, holds shape after wash' — a synthesized quality signal, not just a review count.",
      trace: { findingId: "INT-P4", summary: "A synthesized verdict from many reviews, not just a raw review count." },
    },
    {
      id: "qes-2",
      name: "Navy Formal Trousers",
      brand: "Northfield",
      category: "Trousers",
      imageUrl: productImage("18_navy_formal_trousers_m"),
      imageAlt: "Navy formal trousers, product photography on plain background",
      price: "₹2,299",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 3),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "medium",
      comparisonRows: [],
      narration: "Reviews split: most say fabric holds up well, a smaller group reports pilling after repeated wash — mixed enough to flag rather than settle.",
      missingForHigherConfidence: "Fewer than 20 reviews mention long-term wear specifically — not enough for a confident quality verdict yet.",
      trace: { findingId: "INT-P4", summary: "Genuinely mixed review evidence — flagged honestly rather than overclaimed." },
    },
    {
      id: "qes-3",
      name: "Black Lace-Up Boots",
      brand: "Northfield",
      category: "Boots",
      imageUrl: productImage("19_black_laceup_boots_m"),
      imageAlt: "Black lace-up boots, product photography on plain background",
      price: "₹3,799",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 14),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "This exact style has under 5 reviews mentioning material or durability — not enough for a synthesized verdict, only individual anecdotes.",
      trace: { findingId: "INT-P4", summary: "Too few reviews yet to synthesize a confident quality verdict." },
    },
    {
      id: "qes-4",
      name: "Brown Leather Tote",
      brand: "Ferro & Hide",
      category: "Bags",
      imageUrl: productImage("20_brown_leather_tote"),
      imageAlt: "Brown leather tote bag, product photography on plain background",
      price: "₹4,999",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 8),
      stock: "low_stock",
      restockedAt: null,
      addedToCartAt: "2026-08-21T11:00:00Z",
      confidence: "high",
      comparisonRows: [],
      narration: "Genuine-leather claim is independently confirmed across 90+ reviews, with consistent 'ages well' language — a strong material-trust signal for a ₹5,000 spend.",
      trace: { findingId: "INT-P4", summary: "Strong, independently-confirmed material evidence for a high-value purchase." },
    },
    {
      id: "qes-5",
      name: "Beige Textured Jacket",
      brand: "Ferro & Hide",
      category: "Jackets",
      imageUrl: productImage("26_beige_textured_jacket_m"),
      imageAlt: "Beige textured jacket, product photography on plain background",
      price: "₹3,599",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 19),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "medium",
      comparisonRows: [],
      narration: "Fabric-quality mentions are positive but sparse for this specific colourway — stronger signal exists for the brand overall than for this exact piece.",
      missingForHigherConfidence: "Reviews for this colourway specifically are limited — most quality mentions are for other colours of the same jacket.",
      trace: { findingId: "INT-P4", summary: "Solid brand-level signal, but a gap in evidence for this specific colourway." },
    },
    {
      id: "qes-6",
      name: "Black Chelsea Boots",
      brand: "Northfield",
      category: "Boots",
      imageUrl: productImage("29_black_chelsea_boots_m"),
      imageAlt: "Black Chelsea boots, product photography on plain background",
      price: "₹3,299",
      group: "buying_soon",
      wishlistedAt: hoursAgo(24 * 2),
      stock: "low_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "high",
      comparisonRows: [],
      narration: "Sole-durability and material-quality mentions are consistently positive across 60+ reviews — clears the bar this shopper sets before spending on footwear.",
      trace: { findingId: "INT-P4", summary: "Consistently positive material evidence across a large number of reviews." },
    },
  ];
}

function inspirationMoodboardSaverItems(): WishlistItem[] {
  return [
    {
      id: "ims-1",
      name: "Black Vest & Trousers Set",
      brand: "Studio Denim Co.",
      category: "Sets",
      imageUrl: productImage("21_black_vest_trousers_set_f"),
      imageAlt: "Black vest and trousers co-ord set, product photography on plain background",
      price: "₹2,799",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 40),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "Saved for styling ideas, not a near-term buy — no purchase-intent signal to compare against.",
      trace: { findingId: "INT-P3", summary: "Saved for inspiration — this shopper's wishlist works more like a moodboard than a shopping list." },
    },
    {
      id: "ims-2",
      name: "Olive Embroidered Kurta Set",
      brand: "Suta",
      category: "Sets",
      imageUrl: productImage("22_olive_embroidered_kurta_set_f"),
      imageAlt: "Olive embroidered kurta set, product photography on plain background",
      price: "₹2,899",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 35),
      stock: "low_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "No occasion or intent signal attached — saved during a styling scroll, consistent with discovery starting outside any shopping app.",
      trace: { findingId: "INT-P3", summary: "Discovery started outside the app — the save followed, not a purchase decision." },
    },
    {
      id: "ims-3",
      name: "Printed Blouse",
      brand: "Ilana",
      category: "Blouses",
      imageUrl: productImage("23_printed_blouse_f"),
      imageAlt: "Printed blouse, product photography on plain background",
      price: "₹1,399",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 50),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "No remembered rationale for this save — the wishlist functions as a moodboard here, with no purchase-decision data to compare.",
      trace: { findingId: "INT-P3", summary: "A save with no remembered reason attached — a moodboard entry, not a pending decision." },
    },
    {
      id: "ims-4",
      name: "Cream Pleated Skirt",
      brand: "Suta",
      category: "Skirts",
      imageUrl: productImage("24_cream_pleated_skirt_f"),
      imageAlt: "Cream pleated skirt, product photography on plain background",
      price: "₹1,699",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 45),
      stock: "low_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "Low stock, but inspiration saves like this one don't chase scarcity the way a near-term purchase would.",
      trace: { findingId: "INT-P3", summary: "Availability decay matters less here — this was never near-term purchase intent." },
    },
    {
      // Not a literal transcript example (P1's real quote never mentioned
      // trousers, only jeans) — safe to frame generically for this persona.
      id: "ims-8",
      name: "Olive Trousers",
      brand: "Fieldwalk",
      category: "Trousers",
      imageUrl: productImage("04_olive_trousers_f"),
      imageAlt: "Olive trousers, product photography on plain background",
      price: "₹1,499",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 42),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "Same pattern as the rest of this wishlist — saved as a style idea, with nothing pointing to a near-term purchase.",
      trace: { findingId: "INT-P3", summary: "Consistent with this shopper's broader pattern of saving for ideas, not intent." },
    },
    {
      // Moved from Occasion-Driven Saver — not a literal transcript example
      // (P5 never mentioned a necklace specifically), so reframing it here
      // doesn't contradict any documented evidence, unlike the jeans swap.
      id: "ims-9",
      name: "Layered Gold Necklace",
      brand: "Ilana",
      category: "Jewelry",
      imageUrl: productImage("25_layered_gold_necklace"),
      imageAlt: "Layered gold necklace, product photography on plain background",
      price: "₹1,199",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 33),
      stock: "in_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "A styling accessory saved for how it looks, not for a specific purchase plan — consistent with this shopper's broader pattern.",
      trace: { findingId: "INT-P3", summary: "An accessory saved for inspiration, with no near-term purchase signal behind it." },
    },
    {
      id: "ims-6",
      name: "Taupe Leather Tote",
      brand: "Ferro & Hide",
      category: "Bags",
      imageUrl: productImage("30_taupe_leather_tote"),
      imageAlt: "Taupe leather tote bag, product photography on plain background",
      price: "₹4,299",
      group: "style_ideas",
      wishlistedAt: hoursAgo(24 * 60),
      stock: "out_of_stock",
      restockedAt: null,
      addedToCartAt: null,
      confidence: "insufficient",
      comparisonRows: [],
      narration: "",
      whatWouldHelp: "Now out of stock and never had a purchase-intent signal — a moodboard save that decayed, not a lost sale.",
      trace: { findingId: "INT-P3", summary: "A decayed inspiration save, distinct from a decayed real purchase intent elsewhere in this project." },
    },
  ];
}

export const WISHLIST_BY_PERSONA: Record<string, WishlistItem[]> = {
  price_timing_waiter: priceTimingWaiterItems(),
  fit_cautious_returner: fitCautiousReturnerItems(),
  occasion_driven: occasionDrivenItems(),
  quality_evidence_seeker: qualityEvidenceSeekerItems(),
  inspiration_moodboard_saver: inspirationMoodboardSaverItems(),
};
